server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#   for zipkin
#   docker run -d -p 9411:9411 openzipkin/zipkin:2.23

#   in case of avalabilty use multi eureka servers
#spring:
#  profiles: default
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: default-eureka-server.com
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#---
#
#spring:
#  profiles: eureka-1
#  application:
#    name: eureka-server-clustered
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka-1-server.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-2-server.com:8763/eureka/,http://eureka-3-server.com:8764/eureka/
#
#---
#spring:
#  profiles: eureka-2
#  application:
#    name: eureka-server-clustered
#server:
#  port: 8763
#eureka:
#  instance:
#    hostname: eureka-2-server.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-1-server.com:8762/eureka/,http://eureka-3-server.com:8764/eureka/
#
#---
#spring:
#  profiles: eureka-3
#  application:
#    name: eureka-server-clustered
#server:
#  port: 8764
#eureka:
#  instance:
#    hostname: eureka-3-server.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-1-server.com:8762/eureka/,http://eureka-2-server.com:8763/eureka/